version: '3.6'
services:

  wordpress:
    image: wordpress:php7.3-fpm
    container_name: wordpress
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./site:/var/www/html
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - 'front'
      - 'back'
    restart: always

  mysql:
    image: mariadb:latest
    container_name: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    env_file:
      - .env
    networks:
      - 'back'
    restart: always

  wpcli:
    image: wordpress:cli
    user: xfs
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./site:/var/www/html
    networks:
      - 'back'
    depends_on:
      - mysql
      - wordpress

  caddy:
    image: abiosoft/caddy
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - ./logs/caddy:/var/log/caddy
      - ./site:/var/www/html
    depends_on:
      - wordpress
    networks:
      - 'front'

networks:
  front: {}
  back: {}
